[2022-04-30 10:32:37,001] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: btc_spot_data_dag.aggregated_daily_bids manual__2022-04-30T10:32:22.493856+00:00 [queued]>
[2022-04-30 10:32:37,021] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: btc_spot_data_dag.aggregated_daily_bids manual__2022-04-30T10:32:22.493856+00:00 [queued]>
[2022-04-30 10:32:37,022] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 10:32:37,022] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-30 10:32:37,023] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 10:32:37,045] {taskinstance.py:1270} INFO - Executing <Task(BigQueryOperator): aggregated_daily_bids> on 2022-04-30 10:32:22.493856+00:00
[2022-04-30 10:32:37,053] {standard_task_runner.py:52} INFO - Started process 705 to run task
[2022-04-30 10:32:37,058] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'btc_spot_data_dag', 'aggregated_daily_bids', 'manual__2022-04-30T10:32:22.493856+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpyv59fe4d', '--error-file', '/tmp/tmp4q_j7i14']
[2022-04-30 10:32:37,059] {standard_task_runner.py:80} INFO - Job 59: Subtask aggregated_daily_bids
[2022-04-30 10:32:37,148] {logging_mixin.py:109} INFO - Running <TaskInstance: btc_spot_data_dag.aggregated_daily_bids manual__2022-04-30T10:32:22.493856+00:00 [running]> on host cf4e030da5d2
[2022-04-30 10:32:37,246] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=btc_spot_data_dag
AIRFLOW_CTX_TASK_ID=aggregated_daily_bids
AIRFLOW_CTX_EXECUTION_DATE=2022-04-30T10:32:22.493856+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-30T10:32:22.493856+00:00
[2022-04-30 10:32:37,247] {bigquery.py:655} INFO - Executing: 
            #legacySql
            select sum(bids.size) from `btcspot.btcspot.bids` as bids group by timestamp;
            
[2022-04-30 10:32:37,281] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 661, in execute
    impersonation_chain=self.impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 108, in __init__
    impersonation_chain=impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 219, in __init__
    self.extras = self.get_connection(self.gcp_conn_id).extra_dejson  # type: Dict
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 410, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2022-04-30 10:32:37,294] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=btc_spot_data_dag, task_id=aggregated_daily_bids, execution_date=20220430T103222, start_date=20220430T103237, end_date=20220430T103237
[2022-04-30 10:32:37,327] {standard_task_runner.py:98} ERROR - Failed to execute job 59 for task aggregated_daily_bids (The conn_id `google_cloud_default` isn't defined; 705)
[2022-04-30 10:32:37,351] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-30 10:32:37,401] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
