[2022-04-30 07:58:09,066] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: btc_spot_data_dag.aggregated_daily_asks manual__2022-04-30T07:57:59.795342+00:00 [queued]>
[2022-04-30 07:58:09,088] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: btc_spot_data_dag.aggregated_daily_asks manual__2022-04-30T07:57:59.795342+00:00 [queued]>
[2022-04-30 07:58:09,089] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 07:58:09,089] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-30 07:58:09,090] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 07:58:09,130] {taskinstance.py:1270} INFO - Executing <Task(BigQueryOperator): aggregated_daily_asks> on 2022-04-30 07:57:59.795342+00:00
[2022-04-30 07:58:09,138] {standard_task_runner.py:52} INFO - Started process 2027 to run task
[2022-04-30 07:58:09,145] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'btc_spot_data_dag', 'aggregated_daily_asks', 'manual__2022-04-30T07:57:59.795342+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpo_p9sgk6', '--error-file', '/tmp/tmp2yxmkzdj']
[2022-04-30 07:58:09,148] {standard_task_runner.py:80} INFO - Job 17: Subtask aggregated_daily_asks
[2022-04-30 07:58:09,269] {logging_mixin.py:109} INFO - Running <TaskInstance: btc_spot_data_dag.aggregated_daily_asks manual__2022-04-30T07:57:59.795342+00:00 [running]> on host 7356a9a87c5b
[2022-04-30 07:58:09,368] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=btc_spot_data_dag
AIRFLOW_CTX_TASK_ID=aggregated_daily_asks
AIRFLOW_CTX_EXECUTION_DATE=2022-04-30T07:57:59.795342+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-30T07:57:59.795342+00:00
[2022-04-30 07:58:09,369] {bigquery.py:655} INFO - Executing: select sum(asks.size) from `btcspot.btcspot.asks` as asks group by timestamp;
[2022-04-30 07:58:09,402] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 661, in execute
    impersonation_chain=self.impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 108, in __init__
    impersonation_chain=impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 219, in __init__
    self.extras = self.get_connection(self.gcp_conn_id).extra_dejson  # type: Dict
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 410, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `bigquery_default` isn't defined
[2022-04-30 07:58:09,421] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=btc_spot_data_dag, task_id=aggregated_daily_asks, execution_date=20220430T075759, start_date=20220430T075809, end_date=20220430T075809
[2022-04-30 07:58:09,446] {standard_task_runner.py:98} ERROR - Failed to execute job 17 for task aggregated_daily_asks (The conn_id `bigquery_default` isn't defined; 2027)
[2022-04-30 07:58:09,479] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-30 07:58:09,546] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
