[2022-04-30 07:58:09,148] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: btc_spot_data_dag.aggregated_daily_bids manual__2022-04-30T07:57:59.795342+00:00 [queued]>
[2022-04-30 07:58:09,173] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: btc_spot_data_dag.aggregated_daily_bids manual__2022-04-30T07:57:59.795342+00:00 [queued]>
[2022-04-30 07:58:09,173] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 07:58:09,174] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-30 07:58:09,175] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 07:58:09,202] {taskinstance.py:1270} INFO - Executing <Task(BigQueryOperator): aggregated_daily_bids> on 2022-04-30 07:57:59.795342+00:00
[2022-04-30 07:58:09,210] {standard_task_runner.py:52} INFO - Started process 2028 to run task
[2022-04-30 07:58:09,217] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'btc_spot_data_dag', 'aggregated_daily_bids', 'manual__2022-04-30T07:57:59.795342+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpipmxagwk', '--error-file', '/tmp/tmpb8src5t_']
[2022-04-30 07:58:09,219] {standard_task_runner.py:80} INFO - Job 18: Subtask aggregated_daily_bids
[2022-04-30 07:58:09,326] {logging_mixin.py:109} INFO - Running <TaskInstance: btc_spot_data_dag.aggregated_daily_bids manual__2022-04-30T07:57:59.795342+00:00 [running]> on host 7356a9a87c5b
[2022-04-30 07:58:09,438] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=btc_spot_data_dag
AIRFLOW_CTX_TASK_ID=aggregated_daily_bids
AIRFLOW_CTX_EXECUTION_DATE=2022-04-30T07:57:59.795342+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-30T07:57:59.795342+00:00
[2022-04-30 07:58:09,439] {bigquery.py:655} INFO - Executing: 
            #legacySql
            select sum(bids.size) from `btcspot.btcspot.bids` as bids group by timestamp;
            
[2022-04-30 07:58:09,476] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 661, in execute
    impersonation_chain=self.impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 108, in __init__
    impersonation_chain=impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 219, in __init__
    self.extras = self.get_connection(self.gcp_conn_id).extra_dejson  # type: Dict
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 410, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2022-04-30 07:58:09,494] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=btc_spot_data_dag, task_id=aggregated_daily_bids, execution_date=20220430T075759, start_date=20220430T075809, end_date=20220430T075809
[2022-04-30 07:58:09,527] {standard_task_runner.py:98} ERROR - Failed to execute job 18 for task aggregated_daily_bids (The conn_id `google_cloud_default` isn't defined; 2028)
[2022-04-30 07:58:09,550] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-30 07:58:09,604] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
